#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-antlr4-runtime
Version  : 4.5.3
Release  : 1
URL      : https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.jar
Source0  : https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.jar
Source1  : https://repo1.maven.org/maven2/org/antlr/antlr4-master/4.5.3/antlr4-master-4.5.3.pom
Source2  : https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-antlr4-runtime-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-antlr4-runtime package.
Group: Data

%description data
data components for the mvn-antlr4-runtime package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/antlr/antlr4-runtime/4.5.3
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/antlr/antlr4-runtime/4.5.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/antlr/antlr4-master/4.5.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/antlr/antlr4-master/4.5.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/antlr/antlr4-runtime/4.5.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/antlr/antlr4-runtime/4.5.3


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/antlr/antlr4-master/4.5.3/antlr4-master-4.5.3.pom
/usr/share/java/.m2/repository/org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.jar
/usr/share/java/.m2/repository/org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.pom
